package handlers

import (
	"fmt"
	"io"
	"log/slog"
	"net/http"
	"strconv"
	"strings"
	"time"

	crypto "github.com/bsv-blockchain/go-sdk/primitives/hash"
	"github.com/bsv-blockchain/go-uhrp-storage-server/internal/server/responses"
	"github.com/bsv-blockchain/go-uhrp-storage-server/internal/storage"
	walletpkg "github.com/bsv-blockchain/go-uhrp-storage-server/internal/wallet"
)

// PutHandler handles PUT /put requests for file upload.
type PutHandler struct {
	Store          *storage.FileStore
	WalletProvider *walletpkg.Provider
	HostingDomain  string
	Logger         *slog.Logger
}

// ServeHTTP handles the /put endpoint request for file upload.
// @Summary Upload a file
// @Description Upload a file's binary content using a pre-signed URL generated by the /upload endpoint.
// @Accept application/octet-stream
// @Produce json
// @Param uploader query string true "Uploader's identity key"
// @Param objectID query string true "Unique object identifier"
// @Param fileSize query string true "Expected file size in bytes"
// @Param expiry query string true "HMAC expiry timestamp"
// @Param hmac query string true "HMAC signature validating the upload request"
// @Success 200 {object} map[string]string "Success response"
// @Failure 400 {object} responses.ErrorResponse
// @Failure 401 {object} responses.ErrorResponse
// @Failure 500 {object} responses.ErrorResponse
// @Router /put [put]
func (h *PutHandler) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	q := r.URL.Query()
	uploader := q.Get("uploader")
	objectID := q.Get("objectID")
	fileSizeStr := q.Get("fileSize")
	expiry := q.Get("expiry")
	hmac := q.Get("hmac")

	if objectID == "" || fileSizeStr == "" || expiry == "" || hmac == "" {
		responses.WriteError(w, http.StatusBadRequest, "", "Missing required query parameters")
		return
	}

	body, err := io.ReadAll(r.Body)
	if err != nil {
		responses.WriteError(w, http.StatusBadRequest, "", "Failed to read request body")
		return
	}
	defer r.Body.Close()

	fileSize, _ := strconv.ParseInt(fileSizeStr, 10, 64)
	if fileSize != int64(len(body)) {
		responses.WriteError(w, http.StatusBadRequest, "", "Size mismatch")
		return
	}

	if err := h.WalletProvider.VerifyUploaderHMAC(r.Context(), fileSizeStr, objectID, expiry, uploader, hmac); err != nil {
		if strings.Contains(err.Error(), "invalid HMAC") {
			responses.WriteError(w, http.StatusUnauthorized, "ERR_UNAUTHORIZED", "Invalid HMAC")
		} else {
			responses.WriteError(w, http.StatusInternalServerError, "ERR_HMAC_VERIFY", "HMAC verification failed")
		}
		return
	}

	if h.Store.Exists(objectID) {
		responses.WriteError(w, http.StatusBadRequest, "", "File exists")
		return
	}

	if err := h.Store.Write(objectID, body); err != nil {
		responses.WriteError(w, http.StatusInternalServerError, "ERR_INTERNAL", "Failed to write file")
		return
	}

	if strings.HasPrefix(h.HostingDomain, "localhost") {
		slog.Debug("Not advertising, localhost")
		responses.WriteError(w, http.StatusInternalServerError, "ERR_INTERNAL", "No advertising in localhost.")
		return
	}

	hash := crypto.Sha256(body)
	contentType := r.Header.Get("Content-Type")
	if contentType == "" {
		contentType = "application/octet-stream"
	}

	var expiryInt int64
	if t, err := time.Parse(time.RFC3339, expiry); err == nil {
		expiryInt = t.Unix()
	} else {
		expiryInt, err = strconv.ParseInt(expiry, 10, 64)
		if err != nil {
			responses.WriteError(w, http.StatusBadRequest, "", "Invalid expiry")
			return
		}
	}

	err = h.WalletProvider.CreateAdvertisement(r.Context(), h.WalletProvider.OverlayNetwork(), walletpkg.CreateAdParams{
		Hash:          hash,
		URL:           fmt.Sprintf("https://%s/cdn/%s", h.HostingDomain, objectID),
		ExpirySecs:    expiryInt,
		ContentType:   contentType,
		ContentLength: fileSize,
		ObjectID:      objectID,
		Uploader:      uploader,
	})

	if err != nil {
		h.Logger.Error("Failed to create UHRP advertisement", "error", err)
		responses.WriteError(w, http.StatusInternalServerError, "ERR_INTERNAL", "Failed to broadcast advertisement")
		return
	}

	responses.WriteJSON(w, http.StatusOK, map[string]string{"status": "success"})
}
